version: '3.9'
services:
  node:
    image: node:18
    working_dir: /usr/src/app
    entrypoint: /bin/bash
    volumes:
      - type: bind
        source: $PWD
        target: /usr/src/app
    ports:
      - "8080:3000"
